"""Initial migration - create all 12 tables

Revision ID: c69d77625ee9
Revises: 
Create Date: 2025-10-06 20:40:48.763076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c69d77625ee9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('idx_active', 'categories', ['is_active', 'display_order'], unique=False)
    op.create_table('providers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('service_pincodes', sa.JSON(), nullable=True),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_bookings', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_active', 'providers', ['is_active', 'is_verified'], unique=False)
    op.create_index('idx_mobile', 'providers', ['mobile'], unique=False)
    op.create_index(op.f('ix_providers_mobile'), 'providers', ['mobile'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('wallet_balance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('referral_code', sa.String(length=20), nullable=True),
    sa.Column('referred_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['referred_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mobile', 'users', ['mobile'], unique=False)
    op.create_index('idx_referral', 'users', ['referral_code'], unique=False)
    op.create_index(op.f('ix_users_mobile'), 'users', ['mobile'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_table('addresses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=False),
    sa.Column('contact_name', sa.String(length=100), nullable=True),
    sa.Column('contact_mobile', sa.String(length=15), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pincode', 'addresses', ['pincode'], unique=False)
    op.create_index('idx_user', 'addresses', ['user_id'], unique=False)
    op.create_table('bookings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('payment_gateway_order_id', sa.String(length=100), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('payment_method', sa.Enum('CARD', 'UPI', 'WALLET', 'CASH', name='paymentmethod'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sgst', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('igst', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_gst', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('convenience_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_partial', sa.Boolean(), nullable=False),
    sa.Column('partial_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_settlement', sa.Enum('PENDING', 'COMPLETE', 'FAILED', 'INPROGRESS', name='settlementstatus'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED', name='bookingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_index('idx_created', 'bookings', ['created_at'], unique=False)
    op.create_index('idx_payment', 'bookings', ['payment_status'], unique=False)
    op.create_index('idx_settlement', 'bookings', ['is_settlement'], unique=False)
    op.create_index('idx_status', 'bookings', ['status'], unique=False)
    op.create_index('idx_user', 'bookings', ['user_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='messagerole'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('intent', sa.String(length=50), nullable=True),
    sa.Column('intent_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('agent_calls', sa.JSON(), nullable=True, comment='Array of agent execution details'),
    sa.Column('provenance', sa.JSON(), nullable=True, comment='Sources used: SQL tables, vector docs, etc'),
    sa.Column('grounding_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('faithfulness_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('relevancy_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('flagged_for_review', sa.Boolean(), nullable=False),
    sa.Column('review_reason', sa.String(length=255), nullable=True),
    sa.Column('channel', sa.Enum('WEB', 'MOBILE', 'WHATSAPP', name='channel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_created', 'conversations', ['created_at'], unique=False)
    op.create_index('idx_flagged', 'conversations', ['flagged_for_review'], unique=False)
    op.create_index('idx_intent', 'conversations', ['intent'], unique=False)
    op.create_index('idx_session', 'conversations', ['session_id'], unique=False)
    op.create_index('idx_user', 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_table('priority_queue',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('reviewed_by', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('intent_type', sa.Enum('COMPLAINT', 'REFUND', 'CANCELLATION', 'BOOKING', name='intenttype'), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('sentiment_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('message_snippet', sa.Text(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_priority', 'priority_queue', ['is_reviewed', 'priority_score', 'created_at'], unique=False)
    op.create_index('idx_reviewed_by', 'priority_queue', ['reviewed_by'], unique=False)
    op.create_table('subcategories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category', 'subcategories', ['category_id', 'is_active'], unique=False)
    op.create_index('unique_slug', 'subcategories', ['category_id', 'slug'], unique=True)
    op.create_table('complaints',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_to', sa.BigInteger(), nullable=True),
    sa.Column('resolved_by', sa.BigInteger(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('complaint_type', sa.Enum('SERVICE_QUALITY', 'PROVIDER_BEHAVIOR', 'BILLING', 'DELAY', 'CANCELLATION_ISSUE', 'REFUND_ISSUE', 'OTHER', name='complainttype'), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='complaintpriority'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'ESCALATED', name='complaintstatus'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('response_due_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_due_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assigned', 'complaints', ['assigned_to', 'status'], unique=False)
    op.create_index('idx_booking', 'complaints', ['booking_id'], unique=False)
    op.create_index('idx_created', 'complaints', ['created_at'], unique=False)
    op.create_index('idx_priority', 'complaints', ['priority'], unique=False)
    op.create_index('idx_sla', 'complaints', ['response_due_at', 'resolution_due_at'], unique=False)
    op.create_index('idx_status', 'complaints', ['status'], unique=False)
    op.create_index('idx_user', 'complaints', ['user_id'], unique=False)
    op.create_table('rate_cards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('subcategory_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('strike_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('available_pincodes', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_sub', 'rate_cards', ['category_id', 'subcategory_id', 'is_active'], unique=False)
    op.create_table('booking_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rate_card_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.BigInteger(), nullable=True),
    sa.Column('address_id', sa.BigInteger(), nullable=False),
    sa.Column('service_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('final_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_time_from', sa.Time(), nullable=False),
    sa.Column('scheduled_time_to', sa.Time(), nullable=False),
    sa.Column('actual_start_time', sa.DateTime(), nullable=True),
    sa.Column('actual_end_time', sa.DateTime(), nullable=True),
    sa.Column('cancel_by', sa.Enum('EMPTY', 'PROVIDER', 'CUSTOMER', name='cancelby'), nullable=False),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('payment_status', sa.Enum('UNPAID', 'PAID', 'REFUND', 'FAILED', name='itempaymentstatus'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='itemstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rate_card_id'], ['rate_cards.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_booking', 'booking_items', ['booking_id'], unique=False)
    op.create_index('idx_payment', 'booking_items', ['payment_status'], unique=False)
    op.create_index('idx_provider', 'booking_items', ['provider_id', 'status'], unique=False)
    op.create_index('idx_scheduled', 'booking_items', ['scheduled_date'], unique=False)
    op.create_index('idx_user', 'booking_items', ['user_id'], unique=False)
    op.create_table('complaint_updates',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('complaint_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False, comment='Internal notes not visible to customer'),
    sa.Column('attachments', sa.JSON(), nullable=True, comment='Array of attachment URLs'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_complaint', 'complaint_updates', ['complaint_id'], unique=False)
    op.create_index('idx_created', 'complaint_updates', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_created', table_name='complaint_updates')
    op.drop_index('idx_complaint', table_name='complaint_updates')
    op.drop_table('complaint_updates')
    op.drop_index('idx_user', table_name='booking_items')
    op.drop_index('idx_scheduled', table_name='booking_items')
    op.drop_index('idx_provider', table_name='booking_items')
    op.drop_index('idx_payment', table_name='booking_items')
    op.drop_index('idx_booking', table_name='booking_items')
    op.drop_table('booking_items')
    op.drop_index('idx_category_sub', table_name='rate_cards')
    op.drop_table('rate_cards')
    op.drop_index('idx_user', table_name='complaints')
    op.drop_index('idx_status', table_name='complaints')
    op.drop_index('idx_sla', table_name='complaints')
    op.drop_index('idx_priority', table_name='complaints')
    op.drop_index('idx_created', table_name='complaints')
    op.drop_index('idx_booking', table_name='complaints')
    op.drop_index('idx_assigned', table_name='complaints')
    op.drop_table('complaints')
    op.drop_index('unique_slug', table_name='subcategories')
    op.drop_index('idx_category', table_name='subcategories')
    op.drop_table('subcategories')
    op.drop_index('idx_reviewed_by', table_name='priority_queue')
    op.drop_index('idx_priority', table_name='priority_queue')
    op.drop_table('priority_queue')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_index('idx_user', table_name='conversations')
    op.drop_index('idx_session', table_name='conversations')
    op.drop_index('idx_intent', table_name='conversations')
    op.drop_index('idx_flagged', table_name='conversations')
    op.drop_index('idx_created', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('idx_user', table_name='bookings')
    op.drop_index('idx_status', table_name='bookings')
    op.drop_index('idx_settlement', table_name='bookings')
    op.drop_index('idx_payment', table_name='bookings')
    op.drop_index('idx_created', table_name='bookings')
    op.drop_table('bookings')
    op.drop_index('idx_user', table_name='addresses')
    op.drop_index('idx_pincode', table_name='addresses')
    op.drop_table('addresses')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_mobile'), table_name='users')
    op.drop_index('idx_referral', table_name='users')
    op.drop_index('idx_mobile', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_providers_mobile'), table_name='providers')
    op.drop_index('idx_mobile', table_name='providers')
    op.drop_index('idx_active', table_name='providers')
    op.drop_table('providers')
    op.drop_index('idx_active', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
